(function () {
    const FP8_LINES = [
      {
        id: 'l42',
        line: 42,
        kind: 'memory',
        tag: 'MTE2 预取',
        code: 'DataCopy(aL1, aGM + tileOffset, BLOCK_K * BLOCK_M);',
        short: 'Cube 计算开始前，先把 GM / L2 数据搬入 AIC L1。',
        selectors: ['[data-mem950-node="rail:GM"]', '[data-mem950-node="rail:L2"]', '#mem950-aic [data-aic-node="buffer:L1"]'],
        routes: ['l2-to-aic'],
        path: 'Global Memory → L2 → MTE2 → AIC L1',
        verdict: '访存预取',
        reasons: ['GM 连续读', 'L1 复用窗口', 'MTE2 可搬运'],
        explanation: '这个 tile 会被多个 MMA 步骤复用。先通过 L2 / MTE2 搬入 L1，比重复从 GM 读取更稳定。',
        rewrite: 'DataCopy(aL1, aGM + tileOffset, alignedBlockBytes);',
        metrics: { confidence: '91%', cycles: '-18%', pressure: 'L2 中等' }
      },
      {
        id: 'l48',
        line: 48,
        kind: 'compute',
        tag: 'SIMD / Cube',
        code: 'MmadFp8(cL0C, aL0A, bL0B, repeatM, repeatN, repeatK);',
        short: '对齐后的 FP8 矩阵片段适合走 AIC Cube 路径。',
        selectors: ['#mem950-aic [data-aic-node="buffer:L1"]', '#mem950-aic [data-aic-node="buffer:L0A"]', '#mem950-aic [data-aic-node="buffer:L0B"]', '#mem950-aic [data-aic-node="cube:CUBE"]', '#mem950-aic [data-aic-node="buffer:L0C"]'],
        routes: ['l2-to-aic'],
        path: 'L1 → MTE1 → L0A / L0B → Cube → L0C',
        verdict: 'SIMD / Cube',
        reasons: ['Cube 友好形状', 'stride 已对齐', '支持 FP8 MMAD'],
        explanation: '矩阵片段形状匹配 Cube 执行，两个操作数都能放入 L0A / L0B，不需要额外的标量分支控制。',
        rewrite: 'MmadFp8(cL0C, aL0A, bL0B, mmadShape.m, mmadShape.n, mmadShape.k);',
        metrics: { confidence: '94%', cycles: '-31%', pressure: 'L0 较高' }
      },
      {
        id: 'l57',
        line: 57,
        kind: 'control',
        tag: 'FixPipe 同步',
        code: 'PipeBarrier<PIPE_FIX>();',
        short: '进入向量 epilogue 前，用 FixPipe 保护 L0C 结果顺序。',
        selectors: ['#mem950-aic [data-aic-node="buffer:FP"]', '#mem950-aic [data-aic-node="scheduler:Dispatch"]', '#mem950-aic [data-aic-node="buffer:L0C"]', '#mem950-aiv1 [data-aiv-node="buffer:UB"]'],
        routes: ['aic-to-aiv1'],
        path: 'L0C → FixPipe → 直连 CV 通道 → AIV UB',
        verdict: '混合路径交接',
        reasons: ['L0C 到 UB 交接', '需要顺序保护', '直连 CV 通道'],
        explanation: '结果从 Cube 域进入向量 epilogue，需要明确的流水边界来保证 L0C 到 UB 的交接顺序。',
        rewrite: 'SetFlag<PIPE_FIX, PIPE_V>();\nWaitFlag<PIPE_FIX, PIPE_V>();',
        metrics: { confidence: '88%', cycles: '+2%', pressure: '同步压力低' }
      },
      {
        id: 'l73',
        line: 73,
        kind: 'compute',
        tag: 'SIMD / Vector',
        code: 'Add(outUb, cUb, biasUb, VECTOR_ELEMS);',
        short: 'MMA 后的 bias add 是 AIV 上的稠密向量操作。',
        selectors: ['#mem950-aiv1 [data-aiv-node="buffer:UB"]', '#mem950-aiv1 [data-aiv-node="exec:SIMD"]', '#mem950-aiv1 [data-aiv-node="vector:Vector"]'],
        routes: ['aic-to-aiv1'],
        path: 'AIC L0C → AIV UB → SIMD → Vector',
        verdict: 'SIMD / Vector',
        reasons: ['稠密向量通道', '无分支发散', '数据已在 UB'],
        explanation: '直连通道交接后数据已经在 UB 中，逐元素加法可以稳定映射到 Vector 执行单元。',
        rewrite: 'Add(outUb, cUb, biasUb, alignedVectorElems);',
        metrics: { confidence: '96%', cycles: '-22%', pressure: 'UB 中等' }
      },
      {
        id: 'l82',
        line: 82,
        kind: 'control',
        tag: 'SIMT 条件分支',
        code: 'if (mask[k]) { outUb[k] = relu(outUb[k]); }',
        short: 'mask 控制的分支需要隔离为 SIMT 区域。',
        selectors: ['#mem950-aiv1 [data-aiv-node="buffer:UB"]', '#mem950-aiv1 [data-aiv-node="scalar:Scalar"]', '#mem950-aiv1 [data-aiv-node="exec:SIMT"]', '#mem950-aiv1 [data-aiv-node="vector:Vector"]'],
        routes: [],
        path: 'UB → Scalar 控制 → SIMT Warp Scheduler → Vector',
        verdict: 'SIMT 区域',
        reasons: ['线程分歧已测得', 'mask 密度变化', '标量守卫'],
        explanation: '分支条件随元素变化，工作台会把它标为 SIMT 岛，而不是折叠进稠密 SIMD 向量路径。',
        rewrite: 'Select(outUb, outUb, Zero, maskUb, VECTOR_ELEMS);',
        metrics: { confidence: '83%', cycles: '-9%', pressure: '控制压力中等' }
      },
      {
        id: 'l96',
        line: 96,
        kind: 'memory',
        tag: 'MTE3 写回',
        code: 'DataCopy(outGM + tileOffset, outUb, BLOCK_M * BLOCK_N);',
        short: '向量结果从 UB 通过 MTE3 写回 L2 / GM。',
        selectors: ['#mem950-aiv2 [data-aiv-node="buffer:UB"]', '[data-mem950-node="rail:L2"]', '[data-mem950-node="rail:GM"]'],
        routes: ['aiv2-to-l2'],
        path: 'AIV UB → MTE3 → L2 → Global Memory',
        verdict: '访存写回',
        reasons: ['写回连续', 'UB 排空', 'MTE3 可搬运'],
        explanation: 'epilogue 后最终 tile 已经连续，可以从 AIV UB 经 MTE3 写回 L2 / GM。',
        rewrite: 'DataCopy(outGM + tileOffset, outUb, alignedOutputBytes);',
        metrics: { confidence: '90%', cycles: '-14%', pressure: 'GM 中等' }
      },
      { id: 'l31-tag', line: 31, kind: 'scalar', tag: '地址计算', tagOnly: true },
      { id: 'l32-tag', line: 32, kind: 'loop', tag: 'tile 循环', tagOnly: true },
      { id: 'l33-tag', line: 33, kind: 'scalar', tag: '地址计算', tagOnly: true },
      { id: 'l34-tag', line: 34, kind: 'scalar', tag: 'L1 张量分配', tagOnly: true },
      { id: 'l35-tag', line: 35, kind: 'scalar', tag: 'L1 张量分配', tagOnly: true },
      { id: 'l38-tag', line: 38, kind: 'control', tag: 'MTE2 同步等待', tagOnly: true },
      { id: 'l39-tag', line: 39, kind: 'control', tag: '预取使能', tagOnly: true },
      { id: 'l43-tag', line: 43, kind: 'memory', tag: 'GM→L1 预取', tagOnly: true },
      { id: 'l44-tag', line: 44, kind: 'scalar', tag: 'L1 入队', tagOnly: true },
      { id: 'l45-tag', line: 45, kind: 'scalar', tag: 'L1 入队', tagOnly: true },
      { id: 'l46-tag', line: 46, kind: 'memory', tag: 'L1→L0A 装载', tagOnly: true },
      { id: 'l47-tag', line: 47, kind: 'memory', tag: 'L1→L0B 装载', tagOnly: true },
      { id: 'l49-tag', line: 49, kind: 'scalar', tag: 'L0C 入队', tagOnly: true },
      { id: 'l50-tag', line: 50, kind: 'scalar', tag: 'L0A 释放', tagOnly: true },
      { id: 'l51-tag', line: 51, kind: 'scalar', tag: 'L0B 释放', tagOnly: true },
      { id: 'l54-tag', line: 54, kind: 'memory', tag: 'L0C→UB 交接', tagOnly: true },
      { id: 'l55-tag', line: 55, kind: 'scalar', tag: 'L0C 释放', tagOnly: true },
      { id: 'l56-tag', line: 56, kind: 'control', tag: 'FixPipe 置位', tagOnly: true },
      { id: 'l58-tag', line: 58, kind: 'control', tag: 'FixPipe 等待', tagOnly: true },
      { id: 'l60-tag', line: 60, kind: 'scalar', tag: 'UB 张量分配', tagOnly: true },
      { id: 'l61-tag', line: 61, kind: 'memory', tag: 'GM→UB 读入', tagOnly: true },
      { id: 'l62-tag', line: 62, kind: 'scalar', tag: 'UB 入队', tagOnly: true },
      { id: 'l64-tag', line: 64, kind: 'scalar', tag: 'UB 张量分配', tagOnly: true },
      { id: 'l65-tag', line: 65, kind: 'memory', tag: 'GM→UB 读入', tagOnly: true },
      { id: 'l66-tag', line: 66, kind: 'scalar', tag: 'UB 入队', tagOnly: true },
      { id: 'l68-tag', line: 68, kind: 'scalar', tag: 'UB 张量分配', tagOnly: true },
      { id: 'l71-tag', line: 71, kind: 'scalar', tag: '对齐计算', tagOnly: true },
      { id: 'l72-tag', line: 72, kind: 'memory', tag: '向量对齐', tagOnly: true },
      { id: 'l74-tag', line: 74, kind: 'scalar', tag: 'bias 释放', tagOnly: true },
      { id: 'l77-tag', line: 77, kind: 'scalar', tag: '地址获取', tagOnly: true },
      { id: 'l78-tag', line: 78, kind: 'loop', tag: '元素循环', tagOnly: true },
      { id: 'l79-tag', line: 79, kind: 'control', tag: '控制分支', tagOnly: true },
      { id: 'l80-tag', line: 80, kind: 'control', tag: '预取提示', tagOnly: true },
      { id: 'l84-tag', line: 84, kind: 'scalar', tag: 'mask 释放', tagOnly: true },
      { id: 'l86-tag', line: 86, kind: 'scalar', tag: '地址计算', tagOnly: true },
      { id: 'l87-tag', line: 87, kind: 'scalar', tag: 'UB 入队', tagOnly: true },
      { id: 'l90-tag', line: 90, kind: 'memory', tag: '边界对齐', tagOnly: true },
      { id: 'l91-tag', line: 91, kind: 'control', tag: 'MTE3 同步等待', tagOnly: true },
      { id: 'l94-tag', line: 94, kind: 'scalar', tag: '写回字节计算', tagOnly: true },
      { id: 'l95-tag', line: 95, kind: 'control', tag: 'MTE3 排空使能', tagOnly: true },
      { id: 'l97-tag', line: 97, kind: 'scalar', tag: 'out 释放', tagOnly: true }
    ];

    const FP8_SOURCE_LINES = [
      '#include "tikicpulib.h"',
      '#include "kernel_operator.h"',
      '',
      'using namespace AscendC;',
      '',
      'namespace {',
      'constexpr int32_t BLOCK_M = 128;',
      'constexpr int32_t BLOCK_N = 128;',
      'constexpr int32_t BLOCK_K = 64;',
      'constexpr int32_t VECTOR_ELEMS = 256;',
      'constexpr int32_t kPrefetchStride = 8;',
      'constexpr int32_t kPrefetchAhead  = 32;',
      '}  // namespace',
      '',
      'template <typename DataT, typename AccT>',
      'class FP8MmadMaskedReduce {',
      ' public:',
      '  __aicore__ inline FP8MmadMaskedReduce() = default;',
      '',
      '  __aicore__ inline void Init(GM_ADDR aGm, GM_ADDR bGm,',
      '                              GM_ADDR biasGm, GM_ADDR maskGm,',
      '                              GM_ADDR outGm) {',
      '    aGM = aGm; bGM = bGm;',
      '    biasGM = biasGm; maskGM = maskGm; outGM = outGm;',
      '    pipe.InitBuffer(aL1Que, 1, BLOCK_K * BLOCK_M * sizeof(DataT));',
      '    pipe.InitBuffer(bL1Que, 1, BLOCK_K * BLOCK_N * sizeof(DataT));',
      '    pipe.InitBuffer(cL0CQue, 1, BLOCK_M * BLOCK_N * sizeof(AccT));',
      '  }',
      '',
      '  __aicore__ inline void Process() {',
      '    const int32_t tileCount = CeilDiv(M, BLOCK_M);',
      '    for (int32_t tile = 0; tile < tileCount; ++tile) {',
      '      const int32_t tileOffset = tile * BLOCK_M * K;',
      '      LocalTensor<DataT> aL1 = aL1Que.AllocTensor<DataT>();',
      '      LocalTensor<DataT> bL1 = bL1Que.AllocTensor<DataT>();',
      '      const int32_t aBytes = BLOCK_K * BLOCK_M;',
      '      const int32_t bBytes = BLOCK_K * BLOCK_N;',
      '      WaitFlag<PIPE_MTE2, PIPE_M>();',
      '      EnableMte2Prefetch(aL1Que);',
      '',
      '      // 把 tile A 从 GM/L2 装入 AIC L1，供后续 MMA 复用',
      '      DataCopy(aL1, aGM + tileOffset, BLOCK_K * BLOCK_M);',
      '      DataCopy(bL1, bGM + tileOffset, BLOCK_K * BLOCK_N);',
      '      aL1Que.EnQue(aL1);',
      '      bL1Que.EnQue(bL1);',
      '      LocalTensor<DataT> aL0A = LoadL0A(aL1, mmadShape);',
      '      LocalTensor<DataT> bL0B = LoadL0B(bL1, mmadShape);',
      '      MmadFp8(cL0C, aL0A, bL0B, repeatM, repeatN, repeatK);',
      '      cL0CQue.EnQue(cL0C);',
      '      FreeL0A(aL0A);',
      '      FreeL0B(bL0B);',
      '',
      '      // Cube 完成，准备交接到 Vector epilogue',
      '      LocalTensor<AccT> cUb = TransferToVector(cL0C);',
      '      ReleaseL0C(cL0C);',
      '      SetFlag<PIPE_FIX, PIPE_V>();',
      '      PipeBarrier<PIPE_FIX>();',
      '      WaitFlag<PIPE_FIX, PIPE_V>();',
      '',
      '      LocalTensor<AccT> biasUb = biasQue.AllocTensor<AccT>();',
      '      DataCopy(biasUb, biasGM + tile * BLOCK_N, BLOCK_N);',
      '      biasQue.EnQue(biasUb);',
      '',
      '      LocalTensor<DataT> maskUb = maskQue.AllocTensor<DataT>();',
      '      DataCopy(maskUb, maskGM + tile * BLOCK_N, BLOCK_N);',
      '      maskQue.EnQue(maskUb);',
      '',
      '      LocalTensor<AccT> outUb = outQue.AllocTensor<AccT>();',
      '',
      '      // Bias add：稠密向量加法，AIV SIMD 通道',
      '      const int32_t biasElems = AlignTo(VECTOR_ELEMS, 8);',
      '      AlignVectorIo(outUb, cUb, biasElems);',
      '      Add(outUb, cUb, biasUb, VECTOR_ELEMS);',
      '      biasQue.FreeTensor(biasUb);',
      '',
      '      // mask 控制的逐元素分支，会被识别为 SIMT 区域',
      '      const auto* mask = maskUb.GetPhyAddr();',
      '      for (int32_t k = 0; k < VECTOR_ELEMS; ++k) {',
      '        if (k % kPrefetchStride == 0) {',
      '          PrefetchHint(maskUb, k + kPrefetchAhead);',
      '        }',
      '        if (mask[k]) { outUb[k] = relu(outUb[k]); }',
      '      }',
      '      maskQue.FreeTensor(maskUb);',
      '',
      '      const int32_t outOffset = tile * BLOCK_M * N;',
      '      outQue.EnQue(outUb);',
      '',
      '      // 写回前对齐边界，避免非对齐 MTE3 拖慢',
      '      AlignBoundary(outUb, BLOCK_M * BLOCK_N);',
      '      WaitFlag<PIPE_V, PIPE_MTE3>();',
      '',
      '      // 经 MTE3 写回 L2 / GM，完成本 tile',
      '      const int32_t writeBytes = AlignTo(BLOCK_M * BLOCK_N, 32);',
      '      EnableMte3Drain(outQue);',
      '      DataCopy(outGM + tileOffset, outUb, BLOCK_M * BLOCK_N);',
      '      outQue.FreeTensor(outUb);',
      '    }',
      '  }',
      '};'
    ];


    window.registerWorkbenchKernel({
      id: 'fp8_mmad_masked_reduce',
      name: 'fp8_mmad_masked_reduce.tik',
      label: 'fp8_mmad_masked_reduce',
      path: 'kernels/fp8_mmad_masked_reduce.tik',
      summary: 'FP8 MMAD + masked epilogue',
      target: 'Ascend 950B',
      analysis: 'T2 静态 + 画像',
      verdict: '混合路径',
      defaultTier: 't2',
      selectedId: 'l42',
      sourceLines: FP8_SOURCE_LINES,
      annotations: FP8_LINES
    });
})();
