- version: __APP_VERSION__
  model: claude-sonnet-4-5
  alias: sonnet-4.5
  provider: anthropic
  max_tokens: 8192
  temperature: 0.1
  context_window: 200000
  input_cost_per_mtok: 3.00
  output_cost_per_mtok: 15.00
  rate_config:
    requests_per_second: 16.67
    input_tokens_per_second: 1333.33
    output_tokens_per_second: 266.67
    check_every_n_seconds: 0.05
    max_bucket_size: 100

- version: __APP_VERSION__
  model: claude-haiku-4-5
  alias: haiku-4.5-thinking
  provider: anthropic
  max_tokens: 10000
  temperature: 1
  context_window: 200000
  input_cost_per_mtok: 1.00
  output_cost_per_mtok: 5.00
  extended_reasoning:
    type: enabled
    budget_tokens: 2000
  rate_config:
    requests_per_second: 16.67
    input_tokens_per_second: 1333.33
    output_tokens_per_second: 266.67
    check_every_n_seconds: 0.05
    max_bucket_size: 100

- version: __APP_VERSION__
  model: claude-haiku-4-5
  alias: haiku-4.5
  provider: anthropic
  max_tokens: 10000
  temperature: 0.1
  context_window: 200000
  input_cost_per_mtok: 1.00
  output_cost_per_mtok: 5.00
  rate_config:
    requests_per_second: 16.67
    input_tokens_per_second: 1333.33
    output_tokens_per_second: 266.67
    check_every_n_seconds: 0.05
    max_bucket_size: 100
